{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopandas\n",
      "  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)\n",
      "Collecting pyproj>=2.2.0\n",
      "  Using cached pyproj-3.3.0.tar.gz (217 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpyx4hljww\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4752ec61fa6445c382366abf477cdba7\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e4/36/c151d658ca1a1ccfd5ed82ac3b41d13c36cbd0687da97ac1beaeb3381fa8/pyproj-3.3.0.tar.gz#sha256=ce8bfbc212729e9a643f5f5d77f7a93394e032eda1e2d8799ae902d08add747e (from https://pypi.org/simple/pyproj/) (requires-python:>=3.8). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpyx4hljww Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.2.1.tar.gz (213 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpsbd4jaqa\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_b3c63d4a7e764293bde8419efc5fe45f\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/02/48/9d64166dfbb98d515655c3d28bce68f4b984a96c3bfe5ce81b160f16c763/pyproj-3.2.1.tar.gz#sha256=4a936093825ff55b24c1fc6cc093541fcf6d0f6d406589ed699e62048ebf3877 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpsbd4jaqa Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.2.0.tar.gz (212 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnkfng6s3\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_b255417f3544446da243a97d53f70bec\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2e/9f/217f0cfb328b57a5e471e3d8e1eb58376086ffb50ce74f9977b5bb86f56a/pyproj-3.2.0.tar.gz#sha256=48df0d5ab085bd2dc6db3bca79e20bf15b08ffca4f4e42df6d87b566633b800c (from https://pypi.org/simple/pyproj/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnkfng6s3 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.1.0.tar.gz (182 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpjkcajie6\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_548ca6de45234d40ab323483b1acc84b\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7c/1d/20ea3b603db61ccc60f45064a9e00ba2e6263f1de560e33306f6f3d42fcb/pyproj-3.1.0.tar.gz#sha256=67b94f4e694ae33fc90dfb7da0e6b5ed5f671dd0acc2f6cf46e9c39d56e16e1a (from https://pypi.org/simple/pyproj/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpjkcajie6 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.0.1.tar.gz (168 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpcpi_codh\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_37d2a93f29d74e0eb26ee5a6af3c8a0c\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2c/12/7a8cca32506747c05ffd5c6ba556cf8435754af0939906cbcc7fa5802ea3/pyproj-3.0.1.tar.gz#sha256=bfbac35490dd17f706700673506eeb8170f8a2a63fb5878171d4e6eef242d141 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpcpi_codh Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.0.0.post1.tar.gz (663 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpx7u00446\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_7ba8cfc518e1414fa83897dc4bafd3c7\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/17/e5/3f5cdff3e955bcd768cdb0f4236f2d6e022aaa72f57caf7f4d5f552c88fc/pyproj-3.0.0.post1.tar.gz#sha256=a49581629cadd29e61fc061d153a4d62ff28b4063c71fe8ca881eeb98cd22017 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpx7u00446 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-3.0.0.tar.gz (663 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpeqgw_nhd\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_d510a9a1277a440dbcd00207345adcef\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/44/b8/a645507e4188333e15da29a445102ce2621d69788c586b0625ccd16f8a63/pyproj-3.0.0.tar.gz#sha256=539e320d06e5441edadad2e2ab276e1877445eca384fc1c056b5501453d433c2 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpeqgw_nhd Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp46f7s5l8\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6e7ec416e40b4079b36cf7c509805735\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a8/f9/e7876096af700e7987f5e5abffa09b783ab31157083f76cd88c83e3dbe95/pyproj-2.6.1.post1.tar.gz#sha256=4f5b02b4abbd41610397c635b275a8ee4a2b5bc72a75572b98ac6ae7befa471e (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp46f7s5l8 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.6.1.tar.gz (528 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpzwhbtlc4\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_d111fdf4b0e9458da5fd4d54ee2ef2b5\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/33/2a/44d5631fe4ad9396a3eecdb4de36bc0cbc4b9893c63e4552413bd97d3465/pyproj-2.6.1.tar.gz#sha256=52556f245f1112f121091937b47738d1fbcbd0f13be6fb32689de31ab0975d24 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpzwhbtlc4 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.6.0.tar.gz (524 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnvm724rz\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_7fd4945b4da045019649cfb35eabbe7a\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c0/c2/8c7f27e57835782563715970ec73da41dffc5bb93622f86cc7c3626a9317/pyproj-2.6.0.tar.gz#sha256=977542d2f8cf2981cf3ad72cedfebcd6ac56977c7aa830d9b49fa7888b56e83d (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnvm724rz Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.5.0.tar.gz (508 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpw_20ln1n\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_87c7639e224e4799a73792bee33d77c1\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f6/d3/5ccc7a0cb6addf67ae34b1235a075d17e82116d63eb7ed7395cba4d9ff51/pyproj-2.5.0.tar.gz#sha256=ec4b2146ec8fcc93c38fbd1dcb0df06e5737d588fe28d833dfb2b241d2736f54 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpw_20ln1n Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.4.2.post1.tar.gz (463 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmppu36nak0\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4768150720ee4edfa1021e0bf1c9a09d\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/74/ef/ed7575d2eaaee37b1dcbb53fd57a9d581817b9afff88a41724fe8536907b/pyproj-2.4.2.post1.tar.gz#sha256=1da7f86d3b5e80ba3dabfd2c904a41bb6997ad9b55b47a934035492eaa0f331e (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmppu36nak0 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.4.2.tar.gz (463 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmplq2ohnlp\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_51fc11046be2422a84b672d039f9a000\n",
      "  Complete output (1 lines):\n",
      "  proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d9/9b/400cd3b7e85bf4e60e40e6dc414c38e4fc2ded5cb16947068fa450a62ad9/pyproj-2.4.2.tar.gz#sha256=2821f7fdfe4d2c5916e71f80d0f4029d82785f477a11223e70de2db39a1f26dd (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmplq2ohnlp Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.4.1.tar.gz (462 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpkbqck5ab\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6948cd91ddb943baa1064bd25bdc8a32\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/8c/7e/c34acb5abca1916ba0a294df4a90935d6d1cfc446ad1c076986bbf0118d3/pyproj-2.4.1.tar.gz#sha256=817d4b762adee4479200471042e2393f75a8ec2384061979ccfe177b862b4f8b (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpkbqck5ab Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.4.0.tar.gz (460 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp7cod9758\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_9a0e9014360d4805b63dee53529fb6ca\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f6/16/bda05734b5a54060040aba5aefadae896829aab8ff02db11bad967d5bc61/pyproj-2.4.0.tar.gz#sha256=8124fe43d81a7caca43df6930110e2bfd2bd3b82b86587eefd6f6d86a81a658e (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp7cod9758 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.3.1.tar.gz (422 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmphd6cii62\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4e4cabb3edf947ef80132ace44a1af12\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5e/57/e6bc86f9d407e87db4c859590f799bbffb455940783ea3629b3771619c79/pyproj-2.3.1.tar.gz#sha256=92b8cf0703c25f4e197ec8696b1be567ebb33cb8ba542956142a61df6bf1b766 (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmphd6cii62 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.3.0.tar.gz (415 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp0jarse2t\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_b6b2c8d333b0452cb5ae8c01f08fda6d\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/49/94/06c20b7f65a0efc31da7c734ea4c9385a3b26e5aec619a5b83383dffed93/pyproj-2.3.0.tar.gz#sha256=9c50988827076c685ebaf384b7a6993e193c026aad181b6a579f5a3f6915a37d (from https://pypi.org/simple/pyproj/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp0jarse2t Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.2.2.tar.gz (7.2 MB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_dlvm8ut\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_193a8785be7046cba59f0a0286aad7fc\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f5/79/ceb215614d5673ff482a85217499f0030d9a5e2b2a8c68ac32b16df35f97/pyproj-2.2.2.tar.gz#sha256=6f129a00afdd817dbb331af5709221f35012bcc11a23b8c83fa09197c1190786 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_dlvm8ut Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.2.1.tar.gz (382 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmppe8t0qku\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_183d66c028214d7bb5e1875cc2d52300\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7d/41/f0c8e63d20cd56596bfd88a455738629734faa26f26bbdf4d301330748ad/pyproj-2.2.1.tar.gz#sha256=ec89e68a0cf210af0cc2724b5f8601d4b6809ff0f556e16efc8c955e79672f7a (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmppe8t0qku Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.2.0.tar.gz (378 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpuaamee06\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_f8d9bd5ebd084422800d8596454427a7\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/ef/53a7e9e98595baf4d7212aa731fcec256b432a3db60a55b58a027a4d9d47/pyproj-2.2.0.tar.gz#sha256=0a4f793cc93539c2292638c498e24422a2ec4b25cb47545addea07724b2a56e5 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpuaamee06 Check the logs for full command output.\u001b[0m\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.10.1-py2.py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.10.0-py2.py3-none-any.whl (1.0 MB)\n",
      "  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)\n",
      "  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)\n",
      "  Using cached geopandas-0.8.1-py2.py3-none-any.whl (962 kB)\n",
      "  Using cached geopandas-0.8.0-py2.py3-none-any.whl (962 kB)\n",
      "  Using cached geopandas-0.7.0-py2.py3-none-any.whl (928 kB)\n",
      "  Using cached geopandas-0.6.3-py2.py3-none-any.whl (920 kB)\n",
      "Collecting pyproj\n",
      "  Using cached pyproj-2.1.3.tar.gz (521 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnbofpngy\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_7aa4dc6c9a5d4778b2ecfddadd3374ff\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/05/edfcfd0752e1e3fe5e06245863412bb9aa77888143f6c8900dea62aecdc2/pyproj-2.1.3.tar.gz#sha256=99c52788b01a7bb9a88024bf4d40965c0a66a93d654600b5deacf644775f424d (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpnbofpngy Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.1.2.tar.gz (492 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpqie38n35\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_478ba61dd0514840a4adb292f919c997\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7f/d9/62db3608c734fdd02cb5113a89f377a8b012d14beaee6525afc029b590d4/pyproj-2.1.2.tar.gz#sha256=fe1a50be22151ed9798e993c35b58305fe71d03242afc45ff79570e3fa0312e7 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpqie38n35 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.1.1.tar.gz (461 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_hmirz4w\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_dc5e1fea25e641808be3eb8648d87c48\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1c/64/85bd290cd79dc59a8d2a012bbde3091cc6e8bc8d4b025b419e675315cb71/pyproj-2.1.1.tar.gz#sha256=ac6176ba67e9184bb77748f2b31650d9a72ddf45beb1575555abe8160935964d (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_hmirz4w Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.1.0.tar.gz (459 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpdehdhh09\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_2aef11e5267341e9bc0efea10c21e665\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/20/20/73550cc254ffc6168b3890ece3642514cc176b2ec342f08ed695376b4aca/pyproj-2.1.0.tar.gz#sha256=40d9d6ec9b53c1edabe88bc376e7cd2d1cdd3b338be4485390f086f412e4ac7d (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpdehdhh09 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.0.2.tar.gz (407 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_em_oi0s\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_76d184c9e6794cd68221c3db4e23227b\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ea/58/7f28e5aed3538d589e56af564892ff1f5ed5519cff6a1d0ed852b97870df/pyproj-2.0.2.tar.gz#sha256=d9c5cc3df26bfc0fdc27fd70b4fe3475e3c224326fdf53dfd5b7bef1b87f1780 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmp_em_oi0s Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.0.1.tar.gz (408 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpfnjh171m\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_1f84219498654eb09047013ccacc7aaf\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/65/ad/c1367acde6a0a8f5513f8d9fd11d7417cfdc7702caccb483a575be86d87d/pyproj-2.0.1.tar.gz#sha256=f2ac42ee0bf52cd4320c7e2d6793fa7e6a4901612a9e85194590ecf885035e56 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpfnjh171m Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-2.0.0.tar.gz (408 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpds00fvu8\n",
      "       cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_263c2f688ee9493db296ca4c9f415c78\n",
      "  Complete output (1 lines):\n",
      "  Proj executable not found. Please set PROJ_DIR variable.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/53/4b/21643a93e7d33941498087290636e34c6d534aa8baa1ada54cf0d096ffaa/pyproj-2.0.0.tar.gz#sha256=aa8f0fda988353f37831356d82aadafa4b44815d3c4daadcda046f0f345567ce (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: /Users/hanpu/miniconda3/bin/python /Users/hanpu/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/tmpds00fvu8 Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.9.6.tar.gz (2.8 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4dd18963147e4040b60e1508cfed573b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4dd18963147e4040b60e1508cfed573b/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-06iu7pyc\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4dd18963147e4040b60e1508cfed573b/\n",
      "    Complete output (24 lines):\n",
      "    using bundled proj4..\n",
      "    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 117, in _compile\n",
      "        self.spawn(compiler_so + cc_args + [src, '-o', obj] +\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 910, in spawn\n",
      "        spawn(cmd, dry_run=self.dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 36, in spawn\n",
      "        _spawn_posix(cmd, search_path, dry_run=dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 157, in _spawn_posix\n",
      "        raise DistutilsExecError(\n",
      "    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_4dd18963147e4040b60e1508cfed573b/setup.py\", line 86, in <module>\n",
      "        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 574, in compile\n",
      "        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 120, in _compile\n",
      "        raise CompileError(msg)\n",
      "    distutils.errors.CompileError: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/26/8c/1da0580f334718e04f8bbf74f0515a7fb8185ff96b2560ce080c11aa145b/pyproj-1.9.6.tar.gz#sha256=e0c02b1554b20c710d16d673817b2a89ff94738b0b537aead8ecb2edc4c4487b (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.9.5.1.tar.gz (4.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_310ef71043244e9c971b720e5ca6b204/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_310ef71043244e9c971b720e5ca6b204/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-nr1j9296\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_310ef71043244e9c971b720e5ca6b204/\n",
      "    Complete output (24 lines):\n",
      "    using bundled proj4..\n",
      "    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 117, in _compile\n",
      "        self.spawn(compiler_so + cc_args + [src, '-o', obj] +\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 910, in spawn\n",
      "        spawn(cmd, dry_run=self.dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 36, in spawn\n",
      "        _spawn_posix(cmd, search_path, dry_run=dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 157, in _spawn_posix\n",
      "        raise DistutilsExecError(\n",
      "    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_310ef71043244e9c971b720e5ca6b204/setup.py\", line 72, in <module>\n",
      "        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 574, in compile\n",
      "        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 120, in _compile\n",
      "        raise CompileError(msg)\n",
      "    distutils.errors.CompileError: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz#sha256=53fa54c8fa8a1dfcd6af4bf09ce1aae5d4d949da63b90570ac5ec849efaf3ea8 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.9.5.tar.gz (2.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_586c4d1f0b354ba08a5912f9a8964c71/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_586c4d1f0b354ba08a5912f9a8964c71/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-dzmscb9b\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_586c4d1f0b354ba08a5912f9a8964c71/\n",
      "    Complete output (24 lines):\n",
      "    using bundled proj4..\n",
      "    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 117, in _compile\n",
      "        self.spawn(compiler_so + cc_args + [src, '-o', obj] +\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 910, in spawn\n",
      "        spawn(cmd, dry_run=self.dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 36, in spawn\n",
      "        _spawn_posix(cmd, search_path, dry_run=dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 157, in _spawn_posix\n",
      "        raise DistutilsExecError(\n",
      "    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_586c4d1f0b354ba08a5912f9a8964c71/setup.py\", line 72, in <module>\n",
      "        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 574, in compile\n",
      "        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 120, in _compile\n",
      "        raise CompileError(msg)\n",
      "    distutils.errors.CompileError: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e5/d5/bdbe10850da198238cb693019993827e920421eca5d662166f84f3928db6/pyproj-1.9.5.tar.gz#sha256=fbcd42e52ad41774aa15dcd355ecb097bf40104b9cd7f3d96a9ba6c15d12f71f (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.9.4.tar.gz (7.8 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_62d09582b4534a1c854968bd87c212b7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_62d09582b4534a1c854968bd87c212b7/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-xmxmtyvk\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_62d09582b4534a1c854968bd87c212b7/\n",
      "    Complete output (23 lines):\n",
      "    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 117, in _compile\n",
      "        self.spawn(compiler_so + cc_args + [src, '-o', obj] +\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 910, in spawn\n",
      "        spawn(cmd, dry_run=self.dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 36, in spawn\n",
      "        _spawn_posix(cmd, search_path, dry_run=dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 157, in _spawn_posix\n",
      "        raise DistutilsExecError(\n",
      "    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_62d09582b4534a1c854968bd87c212b7/setup.py\", line 15, in <module>\n",
      "        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 574, in compile\n",
      "        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 120, in _compile\n",
      "        raise CompileError(msg)\n",
      "    distutils.errors.CompileError: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/50/a6/87d081407287534106a38033daf8c00763a99f054bb3015423515e480e95/pyproj-1.9.4.tar.gz#sha256=71b4d8c52d781e2b4afe2d3609e9d700cb631ddbf51060bc702644733cc70869 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.9.3.tar.gz (2.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6993baa9a8fb43e4928a4643ef5b67c5/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6993baa9a8fb43e4928a4643ef5b67c5/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-g7frprdl\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6993baa9a8fb43e4928a4643ef5b67c5/\n",
      "    Complete output (23 lines):\n",
      "    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 117, in _compile\n",
      "        self.spawn(compiler_so + cc_args + [src, '-o', obj] +\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 910, in spawn\n",
      "        spawn(cmd, dry_run=self.dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 36, in spawn\n",
      "        _spawn_posix(cmd, search_path, dry_run=dry_run)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/spawn.py\", line 157, in _spawn_posix\n",
      "        raise DistutilsExecError(\n",
      "    distutils.errors.DistutilsExecError: command 'cc' failed with exit status 1\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_6993baa9a8fb43e4928a4643ef5b67c5/setup.py\", line 14, in <module>\n",
      "        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/ccompiler.py\", line 574, in compile\n",
      "        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n",
      "      File \"/Users/hanpu/miniconda3/lib/python3.8/distutils/unixccompiler.py\", line 120, in _compile\n",
      "        raise CompileError(msg)\n",
      "    distutils.errors.CompileError: command 'cc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f9/7f/ee337f570e4c3ef4593709dcb63e813c359184ede249c4f79b761186bd08/pyproj-1.9.3.tar.gz#sha256=912ed86c5e407f091d0f3d076594af4fb569e27c68199b7d71651edd522aaa0c (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.8.1.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_2b2334d1da2e4edb88f1c8d59055f0c5/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_2b2334d1da2e4edb88f1c8d59055f0c5/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-advcgsxj\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_2b2334d1da2e4edb88f1c8d59055f0c5/\n",
      "    Complete output (5 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_2b2334d1da2e4edb88f1c8d59055f0c5/setup.py\", line 7, in <module>\n",
      "        raise KeyError('please set the environment variable PROJ_DIR to point to the location of your proj.4 installation')\n",
      "    KeyError: 'please set the environment variable PROJ_DIR to point to the location of your proj.4 installation'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0d/db/5fa6fe77a2f04c8b7ffb9d1661587114145324199dd273e2d7079655cf77/pyproj-1.8.1.tar.gz#sha256=a9fcdc2c6df7df5b5c60e5c6f10ef968c8a30ba3f80d2bc42963eeb411261c9a (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached pyproj-1.8.0.tar.gz (31 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_74de05a53cd14511a365a37a67429f28/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_74de05a53cd14511a365a37a67429f28/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-zllm9c6s\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_74de05a53cd14511a365a37a67429f28/\n",
      "    Complete output (5 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/pyproj_74de05a53cd14511a365a37a67429f28/setup.py\", line 6, in <module>\n",
      "        raise KeyError('please set the environment variable PROJ_DIR to point to the location of your proj.4 installation')\n",
      "    KeyError: 'please set the environment variable PROJ_DIR to point to the location of your proj.4 installation'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/cd/4e/0bcb33a08ba07f483dfcb8ffc58c02bb2883d14dc81d9da8c4da02efc1b5/pyproj-1.8.0.tar.gz#sha256=e6e4bf81550ce1930253ea46f73023e642514b948602b73e155984351de5b675 (from https://pypi.org/simple/pyproj/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.6.2-py2.py3-none-any.whl (919 kB)\n",
      "  Using cached geopandas-0.6.1-py2.py3-none-any.whl (918 kB)\n",
      "  Using cached geopandas-0.6.0-py2.py3-none-any.whl (918 kB)\n",
      "  Using cached geopandas-0.5.1-py2.py3-none-any.whl (893 kB)\n",
      "Collecting shapely\n",
      "  Using cached Shapely-1.8.1.post1-cp38-cp38-macosx_11_0_arm64.whl (1.0 MB)\n",
      "Requirement already satisfied: pandas in /Users/hanpu/miniconda3/lib/python3.8/site-packages (from geopandas) (1.4.1)\n",
      "Collecting fiona\n",
      "  Using cached Fiona-1.8.21.tar.gz (1.0 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_463f111492c54a4792b5038860722be1/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_463f111492c54a4792b5038860722be1/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-h5drh4zp\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_463f111492c54a4792b5038860722be1/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/67/5c/4e028e84a1f0cb3f8a994217cf2366360ca984dfc1433f6171de527d0dca/Fiona-1.8.21.tar.gz#sha256=3a0edca2a7a070db405d71187214a43d2333a57b4097544a3fcc282066a58bfc (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.20.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1a59c7a2690947ba982a04c87f5f19f5/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1a59c7a2690947ba982a04c87f5f19f5/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-2ffm_o5b\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1a59c7a2690947ba982a04c87f5f19f5/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ec/f7/093890341a7e8fbfcdfa04caf4dfb588ebab32c13ceaa6a3819da79ea106/Fiona-1.8.20.tar.gz#sha256=a70502d2857b82f749c09cb0dea3726787747933a2a1599b5ab787d74e3c143b (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.19.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_b708a09e4e444cd3b4c95363b97e5dca/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_b708a09e4e444cd3b4c95363b97e5dca/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-c2m9farc\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_b708a09e4e444cd3b4c95363b97e5dca/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a0/d9/6042aeb073d11341f7726de0586ff71c13117c34959dcf07bd4ee6d4b93e/Fiona-1.8.19.tar.gz#sha256=b9059e0b29c2e9e6b817e53f941e77e1aca7075f986005d38db307067b60458f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.18.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5972264e03294e1aadb98cc93863008e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5972264e03294e1aadb98cc93863008e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-c4v8y226\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5972264e03294e1aadb98cc93863008e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9f/e8/401cdaa58d862a25c4b3365acf7d2bd7ac77191e3dc9acdcdac0eff20ff0/Fiona-1.8.18.tar.gz#sha256=b732ece0ff8886a29c439723a3e1fc382718804bb057519d537a81308854967a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.17.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c555f82f9cc246c6bfc102256f847442/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c555f82f9cc246c6bfc102256f847442/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-55gcscu0\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c555f82f9cc246c6bfc102256f847442/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz#sha256=716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.16.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_91b25eb78f484c80b5fd63aa832b12b9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_91b25eb78f484c80b5fd63aa832b12b9/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-8hi365ur\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_91b25eb78f484c80b5fd63aa832b12b9/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1e/60/dfc6115a11338d8aa96cacd8c60635223d9c97d61d556c90acc5dfd663fa/Fiona-1.8.16.tar.gz#sha256=fd6dfb65959becc916e9f6928618bfd59c16cdbc413ece0fbac61489cd11255f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.15.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a98794ecabf0428fba48f2b0d6b017c4/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a98794ecabf0428fba48f2b0d6b017c4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-fofhvr6t\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a98794ecabf0428fba48f2b0d6b017c4/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/55/2f/17450ec2c8fcc720a8a3e4d9a383499508475c7cfb90f7eca9fb585ac598/Fiona-1.8.15.tar.gz#sha256=3b1c9b5c834fae2fe947cfaea176db890bc6750d1a6ba9f54d969c19ffcd191e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.14.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9debbeaec2fc4c528f66dbfbf7af6c5e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9debbeaec2fc4c528f66dbfbf7af6c5e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-9_g3u8ip\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9debbeaec2fc4c528f66dbfbf7af6c5e/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5c/fd/5ec54f2d9b3d5dd23dd443fad5630d6b872e2664814c68b856c47e0d65af/Fiona-1.8.14.tar.gz#sha256=6eac038206c89d2cf5f99ea38b81cc228dc21eac5f47870a9a32d453b0007f4d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_8e465776ba5a46caa93884c2f1943872/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_8e465776ba5a46caa93884c2f1943872/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-pq203vmx\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_8e465776ba5a46caa93884c2f1943872/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz#sha256=1a432bf9fd56f089256c010da009c90d4a795c531a848132c965052185336600 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e68714f3149a485eae231697c1db3dad/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e68714f3149a485eae231697c1db3dad/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-ai2szcri\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e68714f3149a485eae231697c1db3dad/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz#sha256=5ec34898c8b983a723fb4e949dd3e0ed7e691c303e51f6bfd61e52ac9ac813ae (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.12.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7b938c441f814b7d9da586cb05e6b51a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7b938c441f814b7d9da586cb05e6b51a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-_iyien8l\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7b938c441f814b7d9da586cb05e6b51a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/97/d8/feab39987296437fbdc3029fb39752a14355d217d73b93471010b8dd63a3/Fiona-1.8.12.tar.gz#sha256=c9266ddf6ae2a64fcea20014ddf27f800ac07584f2fdb09c2a02f3b3a52e371c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.11.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9d224dbd40314762afafb8c00c1279dd/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9d224dbd40314762afafb8c00c1279dd/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-_h3j1s9g\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9d224dbd40314762afafb8c00c1279dd/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9d/f4/0a0ddc6174c4a93679b5f1dd3535e7ef8989828e6d5f86112de681f8c87b/Fiona-1.8.11.tar.gz#sha256=1e7ca9e051f5bffa1c43c70d573da9ca223fc076b84fa73380614fc02b9eb7f6 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.10.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a5f31df3076443518a5ea0f426cb3d9f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a5f31df3076443518a5ea0f426cb3d9f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-q5_otli3\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_a5f31df3076443518a5ea0f426cb3d9f/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/73/f80b491ed8559326fab202a6d6333a3cd6e8be1e9d782bc6c0d03d476457/Fiona-1.8.10.tar.gz#sha256=ff562eb2f3960e21f8c7f050ddd7f47a763869ea14afc2234a40df72666c6a2c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7f190e4df2d247d0a491164565bb718a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7f190e4df2d247d0a491164565bb718a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-th1vd_u3\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_7f190e4df2d247d0a491164565bb718a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9b/52/45e75507660ce0e86176d0f59b659560f687e2c7e9ebf82a10e7dcd2d3b7/Fiona-1.8.9.post2.tar.gz#sha256=210fb038b579fab38f35ddbdd31b9725f4d5099b3edfd4b87c983e5d47b79983 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5bc71ef3fba84272961b1f7ecf500532/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5bc71ef3fba84272961b1f7ecf500532/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-yuuh7rcy\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5bc71ef3fba84272961b1f7ecf500532/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/a4/d9dd7399be809d3990f5000fb6ae43189ea26ae88be1bed3a4c9ddc1becc/Fiona-1.8.9.post1.tar.gz#sha256=d5e0ea0b8addffe9cba4cb59e2bd495b015230e7a1b1597974f5048211930199 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1545096e02ae4c7285111fe41b72dd7d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1545096e02ae4c7285111fe41b72dd7d/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-5imyes5z\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_1545096e02ae4c7285111fe41b72dd7d/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ad/92/dcbd8c54d697c22f299b5af63b6df3acfbd06c6d72e249614c05be99337c/Fiona-1.8.9.tar.gz#sha256=4dd6e2f5327c1174143c7c8594a75d373bc72f2c9a2a6daee312c3186a128add (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.8.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_d2b3390eb7c44a88920808b4f9718a39/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_d2b3390eb7c44a88920808b4f9718a39/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-_vec1v6o\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_d2b3390eb7c44a88920808b4f9718a39/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/94/7f/e288db1ad63d759d494c30caae34f865e0c6927588c490705e91b7134193/Fiona-1.8.8.tar.gz#sha256=711c3be73203b37812992089445a1e4e9d3d6b64e667389f7b15406e15a91e83 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.7.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c86a6d44679a4b75992ece5ab2ebd71a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c86a6d44679a4b75992ece5ab2ebd71a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-37tf0964\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_c86a6d44679a4b75992ece5ab2ebd71a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/78/62/daafd070aebefa639df247705b97f13f7cfad43895581b5cae41bd886709/Fiona-1.8.7.tar.gz#sha256=a55a23615bad3e142d4e4cda97bb5de83c778a80049222e9dffae93c13b5cf93 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.6.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_06df0a18ad25405485c2e3b03fbccece/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_06df0a18ad25405485c2e3b03fbccece/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-7_dlts20\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_06df0a18ad25405485c2e3b03fbccece/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz#sha256=fa31dfe8855b9cd0b128b47a4df558f1b8eda90d2181bff1dd9854e5556efb3e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.5.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9ae72fe40c27413b9a66a111ef31104c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9ae72fe40c27413b9a66a111ef31104c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-kom_bku1\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_9ae72fe40c27413b9a66a111ef31104c/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7b/af/1c2c83c4a8363a4ce9fea817b1910b5e071bed012e18257faa2a0ab3cfe7/Fiona-1.8.5.tar.gz#sha256=4f5cc2d449edbbf693c83e24cdada72de7c41297383d16fcc92387eb445e9d35 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.4.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5b85988eb44c4539bc7611f00dc9218d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5b85988eb44c4539bc7611f00dc9218d/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-xla2epnz\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_5b85988eb44c4539bc7611f00dc9218d/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3a/16/84960540e9fce61d767fd2f0f1d95f4c63e99ab5d8fddc308e8b51b059b8/Fiona-1.8.4.tar.gz#sha256=aec9ab2e3513c9503ec123b1a8573bee55fc6a66e2ac07088c3376bf6738a424 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.3.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_194c0e20ef1345d3a6640ba203dc76bb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_194c0e20ef1345d3a6640ba203dc76bb/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-lsrw5q2g\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_194c0e20ef1345d3a6640ba203dc76bb/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/46/d1/fcdb32513a03abfde0d97fd9782ce0f8cc0540fa6c6ce783e87b94064964/Fiona-1.8.3.tar.gz#sha256=3e831100a23c3b6cd32b98baf0c9e2119d909b44a5cf4533d3625f61dcf2d2b1 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e1e0a94219ab40d3b7e7489fdd6f2714/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e1e0a94219ab40d3b7e7489fdd6f2714/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-wq9kylx_\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_e1e0a94219ab40d3b7e7489fdd6f2714/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/25/50/0466d5d83e1859c5ca38351ee932d64cc5635f9d4dad522879e58f4b0018/Fiona-1.8.2.tar.gz#sha256=4c6419b7ac29136708029f6a44b4ccd458735a4d241016c7b1bab41685c08d8f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.1.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_53842096606340f8a93417d94bb45986/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_53842096606340f8a93417d94bb45986/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-nwm8vlld\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_53842096606340f8a93417d94bb45986/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3e/5f/0c6704efeea2ff3fba7f54cc6ec38070157f21bc1cffa7bdfa7c9f6b8f7a/Fiona-1.8.1.tar.gz#sha256=4c34bb4c5cd788aaf14e5484c3b7de407b1a8a7c7b2d29bbb2e8b37931e83b8d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.0.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/hanpu/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_fd0dda636f9a4585bbac4c733f4cffcd/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_fd0dda636f9a4585bbac4c733f4cffcd/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-pip-egg-info-jee8qctg\n",
      "         cwd: /private/var/folders/gv/vphltdx54zd89jk01h92js380000gn/T/pip-install-dybimowb/fiona_fd0dda636f9a4585bbac4c733f4cffcd/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2a/bd/c1efc2680f338e5941121c776d6323af6b9698ac739e22ba523cee348a7f/Fiona-1.8.0.tar.gz#sha256=20141a9ece06daa7bb4333fba640c2fe39a49f8aca5492d1da8595d41e91844a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.7.13.tar.gz (731 kB)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.5.0-py2.py3-none-any.whl (893 kB)\n",
      "  Using cached geopandas-0.4.1-py2.py3-none-any.whl (922 kB)\n",
      "  Using cached geopandas-0.4.0-py2.py3-none-any.whl (899 kB)\n",
      "  Using cached geopandas-0.3.0-py2.py3-none-any.whl (888 kB)\n",
      "Collecting descartes\n",
      "  Using cached descartes-1.1.0-py3-none-any.whl (5.8 kB)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.2.1-py2.py3-none-any.whl (199 kB)\n",
      "  Using cached geopandas-0.2.tar.gz (212 kB)\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2a/1e/ea0c9ed982a62d693cbebda0da10321361a88d2a44c67292f64ca3675275/geopandas-0.2.tar.gz#sha256=4c5c44d56c7b6f8b250be9a6231b0a2944e0d6a73be54afec4e9e00fa4fe2537 (from https://pypi.org/simple/geopandas/). Requested geopandas from https://files.pythonhosted.org/packages/2a/1e/ea0c9ed982a62d693cbebda0da10321361a88d2a44c67292f64ca3675275/geopandas-0.2.tar.gz#sha256=4c5c44d56c7b6f8b250be9a6231b0a2944e0d6a73be54afec4e9e00fa4fe2537 has inconsistent version: filename has '0.2', but metadata has '0+unknown'\u001b[0m\n",
      "  Using cached geopandas-0.1.1.tar.gz (15 kB)\n",
      "  Using cached geopandas-0.1.0.tar.gz (15 kB)\n",
      "\u001b[31mERROR: Cannot install geopandas==0.1.0, geopandas==0.1.1, geopandas==0.10.0, geopandas==0.10.1, geopandas==0.10.2, geopandas==0.2.1, geopandas==0.3.0, geopandas==0.4.0, geopandas==0.4.1, geopandas==0.5.0, geopandas==0.5.1, geopandas==0.6.0, geopandas==0.6.1, geopandas==0.6.2, geopandas==0.6.3, geopandas==0.7.0, geopandas==0.8.0, geopandas==0.8.1, geopandas==0.8.2 and geopandas==0.9.0 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\n",
      "The conflict is caused by:\n",
      "    geopandas 0.10.2 depends on pyproj>=2.2.0\n",
      "    geopandas 0.10.1 depends on pyproj>=2.2.0\n",
      "    geopandas 0.10.0 depends on pyproj>=2.2.0\n",
      "    geopandas 0.9.0 depends on pyproj>=2.2.0\n",
      "    geopandas 0.8.2 depends on pyproj>=2.2.0\n",
      "    geopandas 0.8.1 depends on pyproj>=2.2.0\n",
      "    geopandas 0.8.0 depends on pyproj>=2.2.0\n",
      "    geopandas 0.7.0 depends on pyproj>=2.2.0\n",
      "    geopandas 0.6.3 depends on pyproj\n",
      "    geopandas 0.6.2 depends on pyproj\n",
      "    geopandas 0.6.1 depends on pyproj\n",
      "    geopandas 0.6.0 depends on pyproj\n",
      "    geopandas 0.5.1 depends on pyproj\n",
      "    geopandas 0.5.0 depends on pyproj\n",
      "    geopandas 0.4.1 depends on pyproj\n",
      "    geopandas 0.4.0 depends on pyproj\n",
      "    geopandas 0.3.0 depends on pyproj\n",
      "    geopandas 0.2.1 depends on pyproj\n",
      "    geopandas 0.1.1 depends on pyproj\n",
      "    geopandas 0.1.0 depends on pyproj\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install geopandas\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import geopandas as gpd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "season_year                                2021\n",
       "week                                         22\n",
       "test_id                                   51821\n",
       "block                     100XX W OHARE AIRPORT\n",
       "trap                                       T910\n",
       "trap_type                                GRAVID\n",
       "test_date               2021-06-03T00:06:00.000\n",
       "number_of_mosquitoes                          3\n",
       "result                                 negative\n",
       "species                          CULEX RESTUANS\n",
       "latitude                                    NaN\n",
       "longitude                                   NaN\n",
       "location                                    NaN\n",
       "Name: 2, dtype: object"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "traps = pd.read_json('data/traps.json')\n",
    "traps.iloc[2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'latitude': '41.681034931122895',\n",
       " 'longitude': '-87.53343646731054',\n",
       " 'human_address': '{\"address\": \"\", \"city\": \"\", \"state\": \"\", \"zip\": \"\"}'}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "traps['location'][55]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "trapLct = []\n",
    "for i in np.arange(0, len(traps)):\n",
    "  if traps['location'][i] not in trapLct:\n",
    "    trapLct.append(traps['location'][i]) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "trapLct = pd.DataFrame(trapLct[1:])[['latitude','longitude']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "trapLct.to_json('data/trap_location.json', orient=\"records\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Forest data\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "forest = gpd.read_file('data/forestry/forestry.shp')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/hanpu/miniconda3/lib/python3.8/site-packages/geopandas/io/file.py:299: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.\n",
      "  pd.Int64Index,\n"
     ]
    }
   ],
   "source": [
    "forest.to_file('data/forest.json')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
  },
  "kernelspec": {
   "display_name": "Python 3.8.9 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
